
CCX      = g++
LIBS     = -L/usr/lib/x86_64-linux-gnu/
INCLUDES = -I/usr/include/

## output file directories ##
OBJDIR   = obj
EXECDIR  = bin

all : main

main:
	$(CXX) -o $(EXECDIR)/main kalmanFilter.cpp main.cpp
