######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 22 13:02:11 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ButtonPad.hpp DebugConsole.hpp MainInterface.hpp SliderWheel.hpp
SOURCES += main.cpp
