######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 23 16:47:34 2016
######################################################################

QT += core gui opengl

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ButtonPad.hpp \
           DebugConsole.hpp \
           MainInterface.hpp \
           SDL-Window.hpp \
           SliderWheel.hpp
SOURCES += main.cpp
