######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 2 19:18:28 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
